import 'package:flutter/material.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedhomewidget/generated/Generated24HrsChangeWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedhomewidget/generated/GeneratedBTCblockWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedhomewidget/generated/GeneratedBottomMenuWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedhomewidget/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedhomewidget/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedhomewidget/generated/GeneratedLine8Widget.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

/* Frame home
    Autogenerated by FlutLab FTF Generator
*/
class GeneratedHomeWidget extends StatelessWidget {
  getCoinData() async {
    var response =
        await http.get(Uri.https('api.coingecko.com', '/api/v3/simple/price', {
      'ids':
          'bitcoin,ethereum,monero,dogecoin,litecoin,eos,bitcoin-cash,1inch,cardano,tron,xrp',
      'vs_currencies': 'usd',
      'include_24hr_change': 'true',
    }));
    var jsonData = jsonDecode(response.body);
    return jsonData;
  }

  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(fit: StackFit.expand, alignment: Alignment.center,
          //overflow: Overflow.visible,
          children: [
            Container(
              width: MediaQuery.of(context).size.width,
              height: 830.0,
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment(1.0000000596046466, 1.0000000596046466),
                  end: Alignment(-1.0, -1.0),
                  stops: [0.0, 1.0],
                  colors: [
                    Color.fromARGB(255, 142, 0, 255),
                    Color.fromARGB(255, 211, 0, 203)
                  ],
                ),
              ),
              child: Stack(fit: StackFit.expand, alignment: Alignment.center,
                  //overflow: Overflow.visible,
                  children: [
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.042666666666666665;

                        final double height =
                            constraints.maxHeight * 0.6946108163121235;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: constraints.maxHeight * 0.006843456015529403,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedFrame2Widget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.042666666666666665;

                        final double height =
                            constraints.maxHeight * 0.6946108163121235;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.9573333333333334,
                              y: constraints.maxHeight * 0.006843456015529403,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedFrame3Widget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 117.5,
                      right: null,
                      bottom: null,
                      width: MediaQuery.of(context).size.width,
                      height: 0.0,
                      child: GeneratedLine8Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 94.0,
                      right: null,
                      bottom: null,
                      width: MediaQuery.of(context).size.width,
                      height: 20.0,
                      child: Generated24HrsChangeWidget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 118,
                      right: null,
                      bottom: null,
                      width: MediaQuery.of(context).size.width,
                      height: MediaQuery.of(context).size.height - (118),
                      child: FutureBuilder(
                        future: getCoinData(),
                        builder: (context, snapshot) {
                          if (snapshot.data == null) {
                            return Container(
                              child: ListView.builder(
                                scrollDirection: Axis.vertical,
                                itemCount: 1,
                                itemBuilder: (BuildContext context, int index) {
                                  return ListTile(
                                    onTap: () {},
                                    title: Row(
                                      children: <Widget>[
                                        Expanded(child: Text("Loading...")),
                                      ],
                                    ),
                                  );
                                },
                              ),
                            );
                          } else {
                            return Container(
                              child: ListView.builder(
                                scrollDirection: Axis.vertical,
                                itemCount: snapshot.data.length,
                                itemBuilder: (BuildContext context, int index) {
                                  return ListTile(
                                    onTap: () {},
                                    title: Row(
                                      children: <Widget>[
                                        Expanded(
                                            child: GeneratedBTCblockWidget(
                                                snapshot.data.keys
                                                    .toList()[index],
                                                snapshot.data[snapshot.data.keys
                                                        .toList()[index]]['usd']
                                                    .toString(),
                                                snapshot.data[snapshot.data.keys
                                                            .toList()[index]]
                                                        ['usd_24h_change']
                                                    .toString())),
                                      ],
                                    ),
                                  );
                                },
                              ),
                            );
                          }
                        },
                      ),
                    ),
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 570.8468627929688,
              right: null,
              bottom: null,
              width: 375.0,
              height: 241.15313720703125,
              child: GeneratedBottomMenuWidget(),
            )
          ]),
    ));
  }
}
