import 'package:flutter/material.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedBarsNavigationBariPhoneCompactLightDefaultWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/Generated700Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedCurrencyUsedWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedLine37Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedGroup176Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedFrame2Widget1.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedVector17Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedAddaBankorCardWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedBarsStatusBariPhoneLightWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/Generated1200Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedVector18Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedVector15Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedLine39Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedINRWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedAccountWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedPhonenumberWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedRectangle47Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedSupportWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedSecurityWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedRectangle46Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedGroup177Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedRectangle44Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedVaibhavbngmailcomWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedGroup114Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedSignOutWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedIndiaWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedLinkedAccountsWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedFrame3Widget1.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedRectangle42Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedAdvancedSecurityWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedCountryWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedVector16Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedRectangle48Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedVector14Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedLine38Widget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedVaibhhavBansalWidget.dart';
import 'package:flutterapp/crypto_20coins_20liveapp/generatedsettingwidget/generated/GeneratedRectangle45Widget.dart';

/* Frame setting
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                return SingleChildScrollView(
                  scrollDirection: Axis.vertical,
                  child: Container(
                      height: 936.0,
                      child: Stack(children: [
                        Container(
                            width: constraints.maxWidth,
                            child: Container(
                              width: 375.0,
                              height: 936.0,
                              decoration: BoxDecoration(
                                gradient: LinearGradient(
                                  begin: Alignment(
                                      1.0000000596046466, 1.0000000596046466),
                                  end: Alignment(-1.0, -1.0),
                                  stops: [0.0, 1.0],
                                  colors: [
                                    Color.fromARGB(255, 142, 0, 255),
                                    Color.fromARGB(255, 211, 0, 203)
                                  ],
                                ),
                              ),
                              child: Stack(
                                  fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  overflow: Overflow.visible,
                                  children: [
                                    Positioned(
                                      left: 0.0,
                                      top: 235.0,
                                      right: null,
                                      bottom: null,
                                      width: 375.0,
                                      height: 701.0,
                                      child: GeneratedRectangle38Widget(),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: 0.0,
                                      bottom: 0.0,
                                      width: null,
                                      height: null,
                                      child: LayoutBuilder(builder:
                                          (BuildContext context,
                                              BoxConstraints constraints) {
                                        final double width =
                                            constraints.maxWidth *
                                                0.042666666666666665;

                                        final double height =
                                            constraints.maxHeight *
                                                0.8675213675213675;

                                        return Stack(children: [
                                          TransformHelper.translate(
                                              x: constraints.maxWidth *
                                                  0.9573333333333334,
                                              y: constraints.maxHeight *
                                                  -0.0010683760683760685,
                                              z: 0,
                                              child: Container(
                                                width: width,
                                                height: height,
                                                child: GeneratedFrame3Widget1(),
                                              ))
                                        ]);
                                      }),
                                    ),
                                    Positioned(
                                      left: -415.0,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: 375.0,
                                      height: 772.0,
                                      child: GeneratedGroup114Widget(),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: 0.0,
                                      bottom: 0.0,
                                      width: null,
                                      height: null,
                                      child: LayoutBuilder(builder:
                                          (BuildContext context,
                                              BoxConstraints constraints) {
                                        final double width =
                                            constraints.maxWidth *
                                                0.042666666666666665;

                                        final double height =
                                            constraints.maxHeight *
                                                0.8675213675213675;

                                        return Stack(children: [
                                          TransformHelper.translate(
                                              x: 0,
                                              y: constraints.maxHeight *
                                                  0.0010683760683760685,
                                              z: 0,
                                              child: Container(
                                                width: width,
                                                height: height,
                                                child: GeneratedFrame2Widget1(),
                                              ))
                                        ]);
                                      }),
                                    ),
                                    Positioned(
                                      left: 14.0,
                                      top: 655.0,
                                      right: null,
                                      bottom: null,
                                      width: 31.0,
                                      height: 23.0,
                                      child: Generated700Widget(),
                                    ),
                                    Positioned(
                                      left: 340.0,
                                      top: 655.0,
                                      right: null,
                                      bottom: null,
                                      width: 39.0,
                                      height: 23.0,
                                      child: Generated1200Widget(),
                                    ),
                                    Positioned(
                                      left: 90.0,
                                      top: 140.0,
                                      right: null,
                                      bottom: null,
                                      width: 197.0,
                                      height: 32.0,
                                      child: GeneratedVaibhhavBansalWidget(),
                                    ),
                                    Positioned(
                                      left: 91.0,
                                      top: 174.0,
                                      right: null,
                                      bottom: null,
                                      width: 198.0,
                                      height: 28.0,
                                      child: GeneratedVaibhavbngmailcomWidget(),
                                    ),
                                    Positioned(
                                      left: 16.0,
                                      top: 273.0,
                                      right: null,
                                      bottom: null,
                                      width: 109.0,
                                      height: 20.0,
                                      child: GeneratedLinkedAccountsWidget(),
                                    ),
                                    Positioned(
                                      left: 16.0,
                                      top: 388.0,
                                      right: null,
                                      bottom: null,
                                      width: 59.0,
                                      height: 23.0,
                                      child: GeneratedAccountWidget(),
                                    ),
                                    Positioned(
                                      left: 16.0,
                                      top: 626.0,
                                      right: null,
                                      bottom: null,
                                      width: 58.0,
                                      height: 23.0,
                                      child: GeneratedSecurityWidget(),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 299.0,
                                      right: null,
                                      bottom: null,
                                      width: 375.0,
                                      height: 58.0,
                                      child: GeneratedRectangle42Widget(),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 415.0,
                                      right: null,
                                      bottom: null,
                                      width: 375.0,
                                      height: 58.0,
                                      child: GeneratedRectangle43Widget(),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 652.0,
                                      right: null,
                                      bottom: null,
                                      width: 375.0,
                                      height: 58.0,
                                      child: GeneratedRectangle46Widget(),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 749.0,
                                      right: null,
                                      bottom: null,
                                      width: 375.0,
                                      height: 58.0,
                                      child: GeneratedRectangle47Widget(),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 807.0,
                                      right: null,
                                      bottom: null,
                                      width: 375.0,
                                      height: 58.0,
                                      child: GeneratedRectangle48Widget(),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 471.0,
                                      right: null,
                                      bottom: null,
                                      width: 375.0,
                                      height: 58.0,
                                      child: GeneratedRectangle44Widget(),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 529.0,
                                      right: null,
                                      bottom: null,
                                      width: 375.0,
                                      height: 58.0,
                                      child: GeneratedRectangle45Widget(),
                                    ),
                                    Positioned(
                                      left: 16.0,
                                      top: 316.0,
                                      right: null,
                                      bottom: null,
                                      width: 167.0,
                                      height: 25.0,
                                      child: GeneratedAddaBankorCardWidget(),
                                    ),
                                    Positioned(
                                      left: 16.0,
                                      top: 431.0,
                                      right: null,
                                      bottom: null,
                                      width: 124.0,
                                      height: 25.0,
                                      child: GeneratedCurrencyUsedWidget(),
                                    ),
                                    Positioned(
                                      left: 16.0,
                                      top: 669.0,
                                      right: null,
                                      bottom: null,
                                      width: 159.0,
                                      height: 25.0,
                                      child: GeneratedAdvancedSecurityWidget(),
                                    ),
                                    Positioned(
                                      left: 16.0,
                                      top: 766.0,
                                      right: null,
                                      bottom: null,
                                      width: 73.0,
                                      height: 28.0,
                                      child: GeneratedSupportWidget(),
                                    ),
                                    Positioned(
                                      left: 16.0,
                                      top: 824.0,
                                      right: null,
                                      bottom: null,
                                      width: 75.0,
                                      height: 25.0,
                                      child: GeneratedSignOutWidget(),
                                    ),
                                    Positioned(
                                      left: 16.0,
                                      top: 488.0,
                                      right: null,
                                      bottom: null,
                                      width: 72.0,
                                      height: 28.0,
                                      child: GeneratedCountryWidget(),
                                    ),
                                    Positioned(
                                      left: 16.0,
                                      top: 546.0,
                                      right: null,
                                      bottom: null,
                                      width: 124.0,
                                      height: 25.0,
                                      child: GeneratedPhonenumberWidget(),
                                    ),
                                    Positioned(
                                      left: 311.0,
                                      top: 431.0,
                                      right: null,
                                      bottom: null,
                                      width: 36.0,
                                      height: 28.0,
                                      child: GeneratedINRWidget(),
                                    ),
                                    Positioned(
                                      left: 300.0,
                                      top: 488.0,
                                      right: null,
                                      bottom: null,
                                      width: 47.0,
                                      height: 28.0,
                                      child: GeneratedIndiaWidget(),
                                    ),
                                    Positioned(
                                      left: 276.0,
                                      top: 309.0,
                                      right: null,
                                      bottom: null,
                                      width: 83.0,
                                      height: 37.0,
                                      child: GeneratedGroup176Widget(),
                                    ),
                                    Positioned(
                                      left: 354.5,
                                      top: 438.5,
                                      right: null,
                                      bottom: null,
                                      width: 4.5,
                                      height: 9.0,
                                      child: GeneratedVector14Widget(),
                                    ),
                                    Positioned(
                                      left: 354.5,
                                      top: 495.0,
                                      right: null,
                                      bottom: null,
                                      width: 4.5,
                                      height: 9.0,
                                      child: GeneratedVector15Widget(),
                                    ),
                                    Positioned(
                                      left: 354.5,
                                      top: 553.0,
                                      right: null,
                                      bottom: null,
                                      width: 4.5,
                                      height: 9.0,
                                      child: GeneratedVector16Widget(),
                                    ),
                                    Positioned(
                                      left: 354.5,
                                      top: 676.0,
                                      right: null,
                                      bottom: null,
                                      width: 4.5,
                                      height: 9.0,
                                      child: GeneratedVector17Widget(),
                                    ),
                                    Positioned(
                                      left: 354.5,
                                      top: 773.0,
                                      right: null,
                                      bottom: null,
                                      width: 4.5,
                                      height: 9.0,
                                      child: GeneratedVector18Widget(),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 471.0,
                                      right: null,
                                      bottom: null,
                                      width: 374.0,
                                      height: 1.0,
                                      child: GeneratedLine37Widget(),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 529.0,
                                      right: null,
                                      bottom: null,
                                      width: 374.0,
                                      height: 1.0,
                                      child: GeneratedLine38Widget(),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 807.0,
                                      right: null,
                                      bottom: null,
                                      width: 374.0,
                                      height: 1.0,
                                      child: GeneratedLine39Widget(),
                                    )
                                  ]),
                            ))
                      ])),
                );
              }),
              Positioned(
                left: 0.0,
                top: 738.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 74.0,
                child: GeneratedGroup177Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.06675293914273255;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.0010683760683760685,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedBarsNavigationBariPhoneCompactLightDefaultWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.04700854700854701;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBarsStatusBariPhoneLightWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
